# Update 'rev' (versions) for all hooks with `pre-commit autoupdate`
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.2.0"
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1000"]
        exclude: ^docs/assets/dashboard/vendor/plotly-2.4.2.min.js
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        # "!!python/name:materialx.*" are not determined correctly, therefore:
        exclude: ^mkdocs.yml
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: check-case-conflict

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [python]
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
