site_name: ParameterSpace
site_description: "Define parameter spaces with conditionalities and priors."
site_url: "https://boschresearch.github.io/parameterspace/"
repo_url: "https://github.com/boschresearch/parameterspace"
repo_name: "boschresearch/parameterspace"

theme:
  name: material
  palette:
    primary: black
    accent: light blue

copyright: |
  <center>
  <p>
    Copyright (c) 2021 - for information on the respective copyright owner
    see the NOTICE file and/or the repository <a href="https://github.com/boschresearch/parameterspace">https://github.com/boschresearch/parameterspace</a>
  </p>
  <p>
    SPDX-License-Identifier: Apache-2.0
  </p>
  <center>

extra:
  version:
    provider: mike

extra_css:
  - assets/extra.css

nav:
  - Overview: index.md
  - Examples:
      - Parameter types: notebooks/example_1.ipynb
      - Simple parameter space: notebooks/example_2_simple_parameterspace.ipynb
      - Conditional parameter space: notebooks/example_3_conditional_spaces.ipynb
  - ... | regex=^((?!generate_references).)*$

plugins:
  - search
  - gen-files:
      # 'module' & 'exclude' throw a "Config value" warnings, as they are custom values
      module: parameterspace
      exclude:
        - "__init__"
      scripts:
        - docs/generate_references.py
  - mkdocs-jupyter
  - awesome-pages
  - mkdocstrings:
      watch: [parameterspace]
      handlers:
        python:
          selection:
            # Do also show members from parent classes,
            # especially useful for the optimizers
            inherited_members: true
            # Including inherited members does unfortunately
            # also show very basic parameters from the pydantic.BaseModel
            # In principle, only those with a docstring are shown,
            # but we do not want to overload the documentation, so we exclude it
            filters:
              # ... every private member (include __gt__, __init__ etc.)
              - "!^_"
          rendering:
            show_root_heading: true
            show_root_full_path: true
            show_object_full_path: false
            show_root_toc_entry: true
            show_root_members_full_path: false
            show_category_heading: false
            show_if_no_docstring: false
            show_source: true
            group_by_category: false
            heading_level: 1
            show_signature_annotations: false

markdown_extensions:
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - assets/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
